// Phase 4 generator: convert every workout's prose into stored block
// structure by running the (test-covered) parser ONCE, at build time.
//   node tools/generate-blocks.mjs           # regenerate src/data/blocks.js
//   node tools/generate-blocks.mjs --report  # also print per-workout summary
//
// The output file is DATA: reviewable, diffable, and hand-fixable. If a
// workout is misinterpreted, correct its entry in src/data/blocks.js (the
// declared structure wins over the parser at runtime).
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseBlocks } from "../src/engine/blocks.js";
import { RAW_DATA } from "../src/data/workouts.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const report = process.argv.includes("--report");

// ── DECLARED CORRECTIONS ──
// Where the parser's inference is wrong, the correct structure is declared
// here and merged over the generated blocks. Reviewed June 2026:
//   #35: "3 rounds (1 min per exercise)" x 4 exercises = 12 min EMOM (parser
//        read "3 rounds" as 3 minutes); exercise list not extracted
//   #71: "21min EMOM - alternating - <3 exercises>" — list not extracted
//   #80: EMOM list not extracted; tabata block lists 5 exercises (parser
//        defaulted stations to 4)
//   #97: "5 rounds EMOM" of 5 numbered stations = 25 min; list not extracted
const OVERRIDES = {
  35: { workoutBlock: 0, timer: { type: "emom", totalSeconds: 720, totalMinutes: 12, label: "12 Min EMOM (3 rounds × 4)",
    exercises: ["15 Weighted Squats", "20 Hammer curls", "10 Thrusters", "10 DB lunge w twists"] } },
  71: { workoutBlock: 1, timer: { type: "emom", totalSeconds: 1260, totalMinutes: 21, label: "EMOM 21 Min",
    exercises: ["15 pull-up rows", "6 sandbag clean and press", "9 burpees"] } },
  80: [
    { workoutBlock: 0, timer: { type: "emom", totalSeconds: 720, totalMinutes: 12, label: "EMOM 12 Min",
      exercises: ["12 push-up", "12 KB Squat"] } },
    { workoutBlock: 1, timer: { type: "tabata", workSeconds: 40, restSeconds: 20, rounds: 3, stations: 5, label: "Tabata 40s/20s",
      exercises: ["KB Swings", "KB High-pull", "KB lunges", "KB Rows", "Burpees"] } },
  ],
  97: { workoutBlock: 0, timer: { type: "emom", totalSeconds: 1500, totalMinutes: 25, label: "EMOM 25 Min (5 rounds × 5)",
    exercises: ["10 KB Swing + 5 Jump SQ", "10 Push-up + 6 step-up", "10 KB rows + 10 Mountain Climbers", "12 Goblet SQ", "30s Plank"] } },
};

const blocksById = {};
const anomalies = [];

for (const w of RAW_DATA) {
  const entry = {};
  entry.workout = parseBlocks(w.workout);
  if (w.core && w.core.trim()) entry.core = parseBlocks(w.core);
  // apply declared corrections
  const ov = OVERRIDES[w.id];
  if (ov) {
    for (const o of Array.isArray(ov) ? ov : [ov]) {
      entry.workout[o.workoutBlock].timer = o.timer;
    }
  }
  blocksById[w.id] = entry;

  // ── anomaly scan: things worth a human look ──
  const kinds = entry.workout.map(b => b.timer.type);
  const fmt = (w.format || "").toUpperCase();
  const flag = msg => anomalies.push(`#${w.id} [${fmt}] ${msg} — kinds: ${kinds.join(",")}`);

  if (fmt === "AMRAP" && !kinds.includes("countdown")) flag("AMRAP format but no countdown block");
  if (fmt === "EMOM" && !kinds.includes("emom")) flag("EMOM format but no emom block");
  if (fmt === "TABATA" && !kinds.includes("tabata")) flag("TABATA format but no tabata block");
  if (fmt === "DEATH BY EMOM" && !kinds.includes("deathby") && !kinds.includes("emom")) flag("DEATH BY format but no deathby/emom block");
  if (fmt === "FIGHT GONE BAD" && !kinds.includes("fgb")) flag("FGB format but no fgb block");
  for (const b of entry.workout) {
    const t = b.timer;
    if (["tabata", "emom", "circuit", "fgb"].includes(t.type) && (!t.exercises || t.exercises.length === 0))
      flag(`${t.type} block with no exercise list`);
    if (t.type === "countdown" && (!t.totalSeconds || t.totalSeconds <= 0)) flag("countdown with no duration");
    if (t.type === "tabata" && (!t.workSeconds || !t.restSeconds)) flag("tabata without work/rest seconds");
  }
}

const header = `// GENERATED by tools/generate-blocks.mjs — the declared block structure
// for every workout. Timers and voice read THIS, not the prose. Safe to
// hand-edit: corrections here override what the parser inferred, and the
// generator never runs automatically. Regenerate: node tools/generate-blocks.mjs
`;
const body = "export const WORKOUT_BLOCKS = {\n" + RAW_DATA.map(w =>
  `${w.id}: ${JSON.stringify(blocksById[w.id])}`
).join(",\n") + "\n};\n";
writeFileSync(join(root, "src", "data", "blocks.js"), header + body, "utf8");

console.log(`Wrote src/data/blocks.js — ${RAW_DATA.length} workouts`);
console.log(`Anomalies for review: ${anomalies.length}`);
anomalies.forEach(a => console.log("  " + a));

if (report) {
  console.log("\n— per-workout summary —");
  for (const w of RAW_DATA) {
    const e = blocksById[w.id];
    const parts = e.workout.map(b => {
      const t = b.timer;
      if (t.type === "countdown") return `countdown ${Math.round((t.totalSeconds||0)/60)}m`;
      if (t.type === "emom") return `emom ${t.totalMinutes}m${t.exercises ? "/" + t.exercises.length + "ex" : ""}`;
      if (t.type === "tabata") return `tabata ${t.workSeconds}/${t.restSeconds}${t.exercises ? " " + t.exercises.length + "ex" : ""}`;
      if (t.type === "circuit") return `circuit ${t.exerciseSeconds}s ${t.exercises ? t.exercises.length + "ex" : ""}`;
      return t.type;
    });
    console.log(`#${String(w.id).padStart(3)} ${(w.format||"").padEnd(15)} ${parts.join(" | ")}${e.core ? "  +core:" + e.core.map(b=>b.timer.type).join(",") : ""}`);
  }
}
